### ISSUE TITLE
Use recommend precomputed DH-Params instead of creating them yourself

### ISSUE THREAD

**Issue by fleaz** [carlbennett/nginx-conf#5]
Hi,
I just saw that you recommend generating long Diffie-Hellman parameters here:
https://github.com/carlbennett/nginx-conf/blob/5707fe0670b4d040c283ef5e4d8adbd82b9cf44c/etc/nginx/conf.d/dhparams.conf#L8

I would suggest to link to the "official" DH-Params from RFC7919 in this file, which got audited and are known good. They also get recommended by Mozilla in their very popular SSL Configuration generator. And by using precomputed ones you can easily just go for the 4096bit version without wasting ages on `openssl dhparam`

Best regards,
Felix

**Comment by carlbennett** [comment]
Resolved in 1cc1a8d5bd797320ef3c04c5a1ead0e2d9a1bf87.
